Clear-Host

function removeTag($line, $tagName) {
	$startTag = "<$tagName>"
	$endTag = "</$tagName>"
	$line = ($line -replace $startTag)
	$line = ($line -replace $endTag)
	return $line
}

function getStatus($temple) {
	$statuses = @{
		 "Abuja Nigeria Temple"="Announced"
		;"Antananarivo Madagascar Temple"="Announced"
		;"Bakersfield California Temple"="Announced"
		;"Barcelona Spain Temple"="Announced"
		;"Beira Mozambique Temple"="Announced"
		;"Benin City Nigeria Temple"="Announced"
		;"Birmingham England Temple"="Announced"
		;"Brazzaville Republic of the Congo Temple"="Announced"
		;"Brisbane Australia South Temple"="Announced"
		;"Brussels Belgium Temple"="Announced"
		;"Budapest Hungary Temple"="Announced"
		;"Buenos Aires City Center Argentina Temple"="Announced"
		;"Busan Korea Temple"="Announced"
		;"Calabar Nigeria Temple"="Announced"
		;"Cancún Mexico Temple"="Announced"
		;"Cape Coast Ghana Temple"="Announced"
		;"Cape Town South Africa Temple"="Announced"
		;"Charlotte North Carolina Temple"="Announced"
		;"Chiclayo Peru Temple"="Announced"
		;"Chihuahua Mexico Temple"="Announced"
		;"Cincinnati Ohio Temple"="Announced"
		;"Coeur d'Alene Idaho Temple"="Announced"
		;"Colorado Springs Colorado Temple"="Announced"
		;"Cuernavaca Mexico Temple"="Announced"
		;"Culiacán Mexico Temple"="Announced"
		;"Cusco Peru Temple"="Announced"
		;"Des Moines Iowa Temple"="Announced"
		;"Dubai United Arab Emirates Temple"="Announced"
		;"Dublin Ireland Temple"="Announced"
		;"Edinburgh Scotland Temple"="Announced"
		;"Eket Nigeria Temple"="Announced"
		;"El Paso Texas Temple"="Announced"
		;"Fairbanks Alaska Temple"="Announced"
		;"Florianópolis Brazil Temple"="Announced"
		;"Goiânia Brazil Temple"="Announced"
		;"Hamburg Germany Temple"="Announced"
		;"Harrisburg Pennsylvania Temple"="Announced"
		;"Honolulu Hawaii Temple"="Announced"
		;"Houston Texas South Temple"="Announced"
		;"Huancayo Peru Temple"="Announced"
		;"Huehuetenango Guatemala Temple"="Announced"
		;"Huntsville Alabama Temple"="Announced"
		;"Iloilo Philippines Temple"="Announced"
		;"Iquitos Peru Temple"="Announced"
		;"Jacksonville Florida Temple"="Announced"
		;"Jakarta Indonesia Temple"="Announced"
		;"João Pessoa Brazil Temple"="Announced"
		;"Juchitán de Zaragoza Mexico Temple"="Announced"
		;"Kahului Hawaii Temple"="Announced"
		;"Kampala Uganda Temple"="Announced"
		;"Kananga Democratic Republic of the Congo Temple"="Announced"
		;"Kumasi Ghana Temple"="Announced"
		;"La Paz Bolivia Temple"="Announced"
		;"Lagos Nigeria Temple"="Announced"
		;"Laoag Philippines Temple"="Announced"
		;"Lehi Utah Temple"="Announced"
		;"Lethbridge Alberta Temple"="Announced"
		;"Lone Mountain Nevada Temple"="Announced"
		;"Luanda Angola Temple"="Announced"
		;"Maceió Brazil Temple"="Announced"
		;"Maputo Mozambique Temple"="Announced"
		;"Maracaibo Venezuela Temple"="Announced"
		;"Mbuji-Mayi Democratic Republic of the Congo Temple"="Announced"
		;"McKinney Texas Temple"="Announced"
		;"Medellín Colombia Temple"="Announced"
		;"Mexico City Benemérito Mexico Temple"="Announced"
		;"Milan Italy Temple"="Announced"
		;"Milwaukee Wisconsin Temple"="Announced"
		;"Missoula Montana Temple"="Announced"
		;"Monrovia Liberia Temple"="Announced"
		;"Naga Philippines Temple"="Announced"
		;"Natal Brazil Temple"="Announced"
		;"Osaka Japan Temple"="Announced"
		;"Oslo Norway Temple"="Announced"
		;"Pachuca Mexico Temple"="Announced"
		;"Piura Peru Temple"="Announced"
		;"Price Utah Temple"="Announced"
		;"Puerto Montt Chile Temple"="Announced"
		;"Queen Creek Arizona Temple"="Announced"
		;"Retalhuleu Guatemala Temple"="Announced"
		;"Roanoke Virginia Temple"="Announced"
		;"Rosario Argentina Temple"="Announced"
		;"Russia Temple"="Announced"
		;"San Jose California Temple"="Announced"
		;"Santa Ana El Salvador Temple"="Announced"
		;"Santiago Dominican Republic Temple"="Announced"
		;"Santiago Philippines Temple"="Announced"
		;"Santos Brazil Temple"="Announced"
		;"São Paulo East Brazil Temple"="Announced"
		;"Savai'i Samoa Temple"="Announced"
		;"Shanghai People's Republic of China Temple"="Announced"
		;"Singapore Temple"="Announced"
		;"Springfield Missouri Temple"="Announced"
		;"Summit New Jersey Temple"="Announced"
		;"Tacoma Washington Temple"="Announced"
		;"Tampa Florida Temple"="Announced"
		;"Teresina Brazil Temple"="Announced"
		;"Toluca Mexico Temple"="Announced"
		;"Tuguegarao City Philippines Temple"="Announced"
		;"Tula Mexico Temple"="Announced"
		;"Tulsa Oklahoma Temple"="Announced"
		;"Ulaanbaatar Mongolia Temple"="Announced"
		;"Uturoa French Polynesia Temple"="Announced"
		;"Vancouver Washington Temple"="Announced"
		;"Victoria British Columbia Temple"="Announced"
		;"Vienna Austria Temple"="Announced"
		;"Viña del Mar Chile Temple"="Announced"
		;"Vitória Brazil Temple"="Announced"
		;"Wellington New Zealand Temple"="Announced"
		;"West Jordan Utah Temple"="Announced"
		;"Winchester Virginia Temple"="Announced"
		;"Yuma Arizona Temple"="Announced"
		;"Aba Nigeria Temple"="Dedicated"
		;"Accra Ghana Temple"="Dedicated"
		;"Adelaide Australia Temple"="Dedicated"
		;"Albuquerque New Mexico Temple"="Dedicated"
		;"Anchorage Alaska Temple"="Dedicated"
		;"Apia Samoa Temple"="Dedicated"
		;"Arequipa Peru Temple"="Dedicated"
		;"Asunción Paraguay Temple"="Dedicated"
		;"Atlanta Georgia Temple"="Dedicated"
		;"Bangkok Thailand Temple"="Dedicated"
		;"Barranquilla Colombia Temple"="Dedicated"
		;"Baton Rouge Louisiana Temple"="Dedicated"
		;"Belém Brazil Temple"="Dedicated"
		;"Bentonville Arkansas Temple"="Dedicated"
		;"Bern Switzerland Temple"="Dedicated"
		;"Billings Montana Temple"="Dedicated"
		;"Birmingham Alabama Temple"="Dedicated"
		;"Bismarck North Dakota Temple"="Dedicated"
		;"Bogotá Colombia Temple"="Dedicated"
		;"Boise Idaho Temple"="Dedicated"
		;"Boston Massachusetts Temple"="Dedicated"
		;"Bountiful Utah Temple"="Dedicated"
		;"Brasília Brazil Temple"="Dedicated"
		;"Brigham City Utah Temple"="Dedicated"
		;"Brisbane Australia Temple"="Dedicated"
		;"Buenos Aires Argentina Temple"="Dedicated"
		;"Calgary Alberta Temple"="Dedicated"
		;"Campinas Brazil Temple"="Dedicated"
		;"Caracas Venezuela Temple"="Dedicated"
		;"Cardston Alberta Temple"="Dedicated"
		;"Casper Wyoming Temple"="Dedicated"
		;"Cebu City Philippines Temple"="Dedicated"
		;"Cedar City Utah Temple"="Dedicated"
		;"Chicago Illinois Temple"="Dedicated"
		;"Ciudad Juárez Mexico Temple"="Dedicated"
		;"Cobán Guatemala Temple"="Dedicated"
		;"Cochabamba Bolivia Temple"="Dedicated"
		;"Colonia Juárez Chihuahua Mexico Temple"="Dedicated"
		;"Columbia River Washington Temple"="Dedicated"
		;"Columbia South Carolina Temple"="Dedicated"
		;"Columbus Ohio Temple"="Dedicated"
		;"Concepción Chile Temple"="Dedicated"
		;"Copenhagen Denmark Temple"="Dedicated"
		;"Córdoba Argentina Temple"="Dedicated"
		;"Curitiba Brazil Temple"="Dedicated"
		;"Dallas Texas Temple"="Dedicated"
		;"Denver Colorado Temple"="Dedicated"
		;"Deseret Peak Utah Temple"="Dedicated"
		;"Detroit Michigan Temple"="Dedicated"
		;"Draper Utah Temple"="Dedicated"
		;"Durban South Africa Temple"="Dedicated"
		;"Edmonton Alberta Temple"="Dedicated"
		;"Feather River California Temple"="Dedicated"
		;"Fort Collins Colorado Temple"="Dedicated"
		;"Fort Lauderdale Florida Temple"="Dedicated"
		;"Fortaleza Brazil Temple"="Dedicated"
		;"Frankfurt Germany Temple"="Dedicated"
		;"Freiberg Germany Temple"="Dedicated"
		;"Fresno California Temple"="Dedicated"
		;"Fukuoka Japan Temple"="Dedicated"
		;"Gilbert Arizona Temple"="Dedicated"
		;"Guadalajara Mexico Temple"="Dedicated"
		;"Guatemala City Guatemala Temple"="Dedicated"
		;"Guayaquil Ecuador Temple"="Dedicated"
		;"Halifax Nova Scotia Temple"="Dedicated"
		;"Hamilton New Zealand Temple"="Dedicated"
		;"Hartford Connecticut Temple"="Dedicated"
		;"Helena Montana Temple"="Dedicated"
		;"Helsinki Finland Temple"="Dedicated"
		;"Hermosillo Sonora Mexico Temple"="Dedicated"
		;"Hong Kong China Temple"="Dedicated"
		;"Houston Texas Temple"="Dedicated"
		;"Idaho Falls Idaho Temple"="Dedicated"
		;"Indianapolis Indiana Temple"="Dedicated"
		;"Johannesburg South Africa Temple"="Dedicated"
		;"Jordan River Utah Temple"="Dedicated"
		;"Kansas City Missouri Temple"="Dedicated"
		;"Kinshasa Democratic Republic of the Congo Temple"="Dedicated"
		;"Kona Hawaii Temple"="Dedicated"
		;"Kyiv Ukraine Temple"="Dedicated"
		;"Laie Hawaii Temple"="Dedicated"
		;"Las Vegas Nevada Temple"="Dedicated"
		;"Layton Utah Temple"="Dedicated"
		;"Lima Peru Los Olivos Temple"="Dedicated"
		;"Lima Peru Temple"="Dedicated"
		;"Lisbon Portugal Temple"="Dedicated"
		;"Logan Utah Temple"="Dedicated"
		;"London England Temple"="Dedicated"
		;"Los Angeles California Temple"="Dedicated"
		;"Louisville Kentucky Temple"="Dedicated"
		;"Lubbock Texas Temple"="Dedicated"
		;"Madrid Spain Temple"="Dedicated"
		;"Manaus Brazil Temple"="Dedicated"
		;"Manhattan New York Temple"="Dedicated"
		;"Manila Philippines Temple"="Dedicated"
		;"Manti Utah Temple"="Dedicated"
		;"McAllen Texas Temple"="Dedicated"
		;"Medford Oregon Temple"="Dedicated"
		;"Melbourne Australia Temple"="Dedicated"
		;"Memphis Tennessee Temple"="Dedicated"
		;"Mendoza Argentina Temple"="Dedicated"
		;"Mérida Mexico Temple"="Dedicated"
		;"Meridian Idaho Temple"="Dedicated"
		;"Mesa Arizona Temple"="Dedicated"
		;"Mexico City Mexico Temple"="Dedicated"
		;"Monterrey Mexico Temple"="Dedicated"
		;"Montevideo Uruguay Temple"="Dedicated"
		;"Monticello Utah Temple"="Dedicated"
		;"Montreal Quebec Temple"="Dedicated"
		;"Moses Lake Washington Temple"="Dedicated"
		;"Mount Timpanogos Utah Temple"="Dedicated"
		;"Nashville Tennessee Temple"="Dedicated"
		;"Nauvoo Illinois Temple"="Dedicated"
		;"Newport Beach California Temple"="Dedicated"
		;"Nuku'alofa Tonga Temple"="Dedicated"
		;"Oakland California Temple"="Dedicated"
		;"Oaxaca Mexico Temple"="Dedicated"
		;"Ogden Utah Temple"="Dedicated"
		;"Okinawa Japan Temple"="Dedicated"
		;"Oklahoma City Oklahoma Temple"="Dedicated"
		;"Oquirrh Mountain Utah Temple"="Dedicated"
		;"Orem Utah Temple"="Dedicated"
		;"Orlando Florida Temple"="Dedicated"
		;"Palmyra New York Temple"="Dedicated"
		;"Panama City Panama Temple"="Dedicated"
		;"Papeete Tahiti Temple"="Dedicated"
		;"Paris France Temple"="Dedicated"
		;"Payson Utah Temple"="Dedicated"
		;"Perth Australia Temple"="Dedicated"
		;"Philadelphia Pennsylvania Temple"="Dedicated"
		;"Phoenix Arizona Temple"="Dedicated"
		;"Pittsburgh Pennsylvania Temple"="Dedicated"
		;"Pocatello Idaho Temple"="Dedicated"
		;"Port-au-Prince Haiti Temple"="Dedicated"
		;"Portland Oregon Temple"="Dedicated"
		;"Porto Alegre Brazil Temple"="Dedicated"
		;"Praia Cape Verde Temple"="Dedicated"
		;"Preston England Temple"="Dedicated"
		;"Provo City Center Temple"="Dedicated"
		;"Provo Utah Rock Canyon Temple"="Dedicated"
		;"Puebla Mexico Temple"="Dedicated"
		;"Quetzaltenango Guatemala Temple"="Dedicated"
		;"Quito Ecuador Temple"="Dedicated"
		;"Raleigh North Carolina Temple"="Dedicated"
		;"Recife Brazil Temple"="Dedicated"
		;"Red Cliffs Utah Temple"="Dedicated"
		;"Redlands California Temple"="Dedicated"
		;"Regina Saskatchewan Temple"="Dedicated"
		;"Reno Nevada Temple"="Dedicated"
		;"Rexburg Idaho Temple"="Dedicated"
		;"Richmond Virginia Temple"="Dedicated"
		;"Rio de Janeiro Brazil Temple"="Dedicated"
		;"Rome Italy Temple"="Dedicated"
		;"Sacramento California Temple"="Dedicated"
		;"Salt Lake Temple"="Dedicated"
		;"Salta Argentina Temple"="Dedicated"
		;"Salvador Brazil Temple"="Dedicated"
		;"San Antonio Texas Temple"="Dedicated"
		;"San Diego California Temple"="Dedicated"
		;"San José Costa Rica Temple"="Dedicated"
		;"San Juan Puerto Rico Temple"="Dedicated"
		;"San Pedro Sula Honduras Temple"="Dedicated"
		;"San Salvador El Salvador Temple"="Dedicated"
		;"Santiago Chile Temple"="Dedicated"
		;"Santo Domingo Dominican Republic Temple"="Dedicated"
		;"São Paulo Brazil Temple"="Dedicated"
		;"Sapporo Japan Temple"="Dedicated"
		;"Saratoga Springs Utah Temple"="Dedicated"
		;"Seattle Washington Temple"="Dedicated"
		;"Seoul Korea Temple"="Dedicated"
		;"Snowflake Arizona Temple"="Dedicated"
		;"Spokane Washington Temple"="Dedicated"
		;"St. George Utah Temple"="Dedicated"
		;"St. Louis Missouri Temple"="Dedicated"
		;"St. Paul Minnesota Temple"="Dedicated"
		;"Star Valley Wyoming Temple"="Dedicated"
		;"Stockholm Sweden Temple"="Dedicated"
		;"Suva Fiji Temple"="Dedicated"
		;"Sydney Australia Temple"="Dedicated"
		;"Taipei Taiwan Temple"="Dedicated"
		;"Tallahassee Florida Temple"="Dedicated"
		;"Tampico Mexico Temple"="Dedicated"
		;"Taylorsville Utah Temple"="Dedicated"
		;"Tegucigalpa Honduras Temple"="Dedicated"
		;"The Gila Valley Arizona Temple"="Dedicated"
		;"The Hague Netherlands Temple"="Dedicated"
		;"Tijuana Mexico Temple"="Dedicated"
		;"Tokyo Japan Temple"="Dedicated"
		;"Toronto Ontario Temple"="Dedicated"
		;"Trujillo Peru Temple"="Dedicated"
		;"Tucson Arizona Temple"="Dedicated"
		;"Tuxtla Gutiérrez Mexico Temple"="Dedicated"
		;"Twin Falls Idaho Temple"="Dedicated"
		;"Urdaneta Philippines Temple"="Dedicated"
		;"Vancouver British Columbia Temple"="Dedicated"
		;"Veracruz Mexico Temple"="Dedicated"
		;"Vernal Utah Temple"="Dedicated"
		;"Villahermosa Mexico Temple"="Dedicated"
		;"Washington D.C. Temple"="Dedicated"
		;"Winnipeg Manitoba Temple"="Dedicated"
		;"Winter Quarters Nebraska Temple"="Dedicated"
		;"Yigo Guam Temple"="Dedicated"
		;"Abidjan Ivory Coast Temple"="Under Construction"
		;"Alabang Philippines Temple"="Under Construction"
		;"Antofagasta Chile Temple"="Under Construction"
		;"Auckland New Zealand Temple"="Under Construction"
		;"Austin Texas Temple"="Under Construction"
		;"Bacolod Philippines Temple"="Under Construction"
		;"Bahía Blanca Argentina Temple"="Under Construction"
		;"Belo Horizonte Brazil Temple"="Under Construction"
		;"Bengaluru India Temple"="Under Construction"
		;"Burley Idaho Temple"="Under Construction"
		;"Cagayan de Oro Philippines Temple"="Under Construction"
		;"Cali Colombia Temple"="Under Construction"
		;"Cleveland Ohio Temple"="Under Construction"
		;"Cody Wyoming Temple"="Under Construction"
		;"Davao Philippines Temple"="Under Construction"
		;"Elko Nevada Temple"="Under Construction"
		;"Ephraim Utah Temple"="Under Construction"
		;"Farmington New Mexico Temple"="Under Construction"
		;"Fort Worth Texas Temple"="Under Construction"
		;"Freetown Sierra Leone Temple"="Under Construction"
		;"Grand Junction Colorado Temple"="Under Construction"
		;"Grand Rapids Michigan Temple"="Under Construction"
		;"Harare Zimbabwe Temple"="Under Construction"
		;"Heber Valley Utah Temple"="Under Construction"
		;"Kaohsiung Taiwan Temple"="Under Construction"
		;"Knoxville Tennessee Temple"="Under Construction"
		;"Lindon Utah Temple"="Under Construction"
		;"Londrina Brazil Temple"="Under Construction"
		;"Lubumbashi Democratic Republic of the Congo Temple"="Under Construction"
		;"Managua Nicaragua Temple"="Under Construction"
		;"Miraflores Guatemala City Guatemala Temple"="Under Construction"
		;"Modesto California Temple"="Under Construction"
		;"Montpelier Idaho Temple"="Under Construction"
		;"Nairobi Kenya Temple"="Under Construction"
		;"Neiafu Tonga Temple"="Under Construction"
		;"Pago Pago American Samoa Temple"="Under Construction"
		;"Phnom Penh Cambodia Temple"="Under Construction"
		;"Port Moresby Papua New Guinea Temple"="Under Construction"
		;"Port Vila Vanuatu Temple"="Under Construction"
		;"Querétaro Mexico Temple"="Under Construction"
		;"Ribeirão Preto Brazil Temple"="Under Construction"
		;"San Luis Potosí Mexico Temple"="Under Construction"
		;"Santa Cruz Bolivia Temple"="Under Construction"
		;"Santiago West Chile Temple"="Under Construction"
		;"Smithfield Utah Temple"="Under Construction"
		;"Syracuse Utah Temple"="Under Construction"
		;"Tacloban City Philippines Temple"="Under Construction"
		;"Tarawa Kiribati Temple"="Under Construction"
		;"Teton River Idaho Temple"="Under Construction"
		;"Torreón Mexico Temple"="Under Construction"
		;"Wichita Kansas Temple"="Under Construction"
		;"Willamette Valley Oregon Temple"="Under Construction"
		;"Yorba Linda California Temple"="Under Construction"
	}
	return $statuses[$temple]
}


# Get the list of all rows in ChurchofJesusChristTemples.kml
$sourceFile = "ChurchofJesusChristTemples2.kml"
Write-Host "Gathering list of objects in $sourceFile..." -NoNewline
$objects = Get-Content -Path $sourceFile
Write-Host " complete" -ForegroundColor Green

# Iterate through each object and process
$json = "{""type"":""FeatureCollection"",""metadata"":{""generated"":1742622518568,""url"":""http://127.0.0.1:5500/index.html"",""title"":""Temples of The Church of Jesus Christ of Latter-day Saints"",""status"":200,""api"":""1.1.1"",""count"":370},""features"":["
$name = ""
$status = ""
$url = ""
$img = ""
$snippet = ""
$date = ""
$coordinates = ""
$description = ""
$desc = $false

$objects | ForEach-Object {
	$line = $_.Trim()
	
	if ($line.StartsWith("<Placemark>")) {
		if ($name -ne "") {
			$json = "$json{""type"":""Feature"",""geometry"":{""type"":""Point"",""coordinates"":[$coordinates]},""properties"":{""name"":""$name"",""status"":""$status"",""url"":""$url"",""img"":""$img"",""address"":""$description"",""snippet"":""$snippet"",""date"":""$date""}},"
		}
		$name = ""
		$status = ""
		$url = ""
		$img = ""
		$snippet = ""
		$date = ""
		$coordinates = ""
		$description = ""
		$desc = $false
	}
	
	if ($line.StartsWith("<name>")) {
		$name = removeTag $line "name"
		$status = getStatus $name
	}
	
	if ($line.StartsWith("<Snippet>")) {
		$snippet = removeTag $line "Snippet"
	}
	
	if ($line.StartsWith("<begin>")) {
		$date = removeTag $line "begin"
	}
	
	if ($line.StartsWith("<coordinates>")) {
		$coordinates = removeTag $line "coordinates"
	}
	
	if (($line.StartsWith("<description>")) -or ($desc -eq $true)) {
		$desc = $true
		if ($line.Contains("</description>")) {
			$desc = $false
		}
		$line = removeTag $line "description"
		$description = "$description$line"
		
		if ($desc -eq $false) {
			$startString = '<\!\[CDATA\['
			$endString = ']]>'
			$description = ($description -replace $startString)
			$description = ($description -replace $endString)
			
			#Get url from anchor tag
			$regex =  '<a\s+(?:[^>]*?\s+)?href=(["''])(.*?)\1'
			if ($description -match $regex) {
				$url = $matches[2]
			}
			
			#Get url for img
			$regex =  '<img\s+(?:[^>]*?\s+)?src=(["''])(.*?)\1'
			if ($description -match $regex) {
				$img = $matches[2]
			}

			#Replace the entire <a> tag with empty string
			$description = $description -replace '<a href="[^"]+"><img[^>]+></a>', ''
			
			#Replace double-quotes in any remaining with double-double quotes
			$description = $description -replace '"', '\"'
			
			#Replace the first <br /><br> - not needed
			$description = $description -replace '<br /><br>', ''
			
		}
	}
	
}

$json = "$json]}"
$json > temples.geojson